# Generated by Django 4.2.3 on 2023-07-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('definition', models.CharField(max_length=200)),
                ('photo', models.FileField(blank=True, null=True, upload_to='card_images')),
                ('last_modified', models.DateField()),
                ('study_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.studyprogram')),
            ],
        ),
    ]
