# Generated by Django 4.2.3 on 2023-07-25 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('definition', models.CharField(max_length=200)),
                ('study_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.studyset')),
            ],
        ),
    ]
