# Generated by Django 4.2.3 on 2023-07-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='photo',
            field=models.FileField(null=True, upload_to='card_images'),
        ),
    ]
