# Generated by Django 4.2.3 on 2023-07-29 10:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_alter_flashcard_last_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='studyprogram',
            name='created_date',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ساخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashcard',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='اخرین تغییر'),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ساخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='اخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='definition',
            field=models.CharField(max_length=200, verbose_name='معنی'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='card_images', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='study_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.studyprogram', verbose_name='برنامه ی مطالعه'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='word',
            field=models.CharField(max_length=200, verbose_name='کلمه'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='عنوان'),
        ),
    ]
