# Generated by Django 4.2.3 on 2023-07-26 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_flashcard_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='study_set',
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='card_images'),
        ),
        migrations.DeleteModel(
            name='StudySet',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='study_program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flashcards.studyprogram'),
            preserve_default=False,
        ),
    ]
